### PR TITLE
Hero Release Patch (DB)

### PR DESCRIPTION
**Pull request by MGatner**

### CODE REVIEW

**Comment by poma** [comment]
Before merging we should add code that actually writes this column

**Comment by MGatner** [comment]
I will but it isn’t live on Heroes-Talents yet so I was going to wait for that to post (probably when Imperius goes live). Current values are on PTR branch if you want to review

**Comment by MGatner** [comment]
heroes-talent has releasePatch live as of https://github.com/heroespatchnotes/heroes-talents/commit/207e4ed359915be4ea3f6b4a77bec347df362d86 - ready for DB migration and updated to fetch.

**Comment by MGatner** [comment]
Need anything else on this?

**Comment by MGatner** [comment]
Bump!

**Pull request merged**
